const $=s=>document.querySelector(s), message=t=>$('#message').textContent=t;
let current;
async function json(path,opt){const r=await fetch(path,opt);const body=await r.text();if(!r.ok)throw Error(body||r.statusText);return body?JSON.parse(body):null}
function row(label, control){const p=document.createElement('p'), l=document.createElement('label');l.textContent=label;l.append(document.createElement('br'),control);p.append(l);return p}
async function assetField(id,label){const select=document.createElement('select');select.name=id;const none=document.createElement('option');none.value='';none.textContent='なし';select.append(none);for(const asset of await json(`/api/profiles/${current.profile.id}/assets/${id}`)){const o=document.createElement('option');o.value=asset;o.textContent=asset;select.append(o)}return row(label,select)}
function checkbox(id,label,checked){const input=document.createElement('input');input.type='checkbox';input.name='scroll_cycle';input.value=id;input.checked=checked;const l=document.createElement('label');l.append(input,' '+label);return row('スクロール中の切替',l)}
async function choose(){current=await json('/api/profiles/'+$('#profile').value);const form=$('#form');form.replaceChildren();if(!current.e233){form.append(row('この車種',document.createTextNode('patterns TOMLを準備してください。')));return}for(const id of ['service','destination','route','through_route','service_change','next_stop']){const group=current.e233.assets[id];form.append(await assetField(id,group.label))}const text=document.createElement('input');text.name='scroll_text';text.type='text';text.value='';form.append(row('スクロール文字',text));const speed=document.createElement('input');speed.name='scroll_speed';speed.type='number';speed.min=1;speed.max=200;speed.value=current.scroll_defaults?.speed_px_per_second??50;form.append(row('スクロール速度 (px/秒)',speed));form.append(checkbox('destination_ja','日本語の種別＋行先',true),checkbox('destination_en','英語の種別＋行先',true),checkbox('route','日本語の種別＋路線名',false),checkbox('through_route','日本語の種別＋直通先路線名',false));const brightness=document.createElement('input');brightness.name='brightness';brightness.type='number';brightness.min=0;brightness.max=100;brightness.value=current.profile.default_brightness??40;form.append(row('輝度 (0〜100)',brightness));$('#status').textContent=current.profile.name}
async function init(){const profiles=await json('/api/profiles');$('#profile').replaceChildren(...profiles.map(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;return o}));if(profiles.length)await choose()}
$('#profile').onchange=()=>choose().catch(e=>message(e.message));
$('#apply').onclick=async()=>{try{const form=new FormData($('#form')),v=Object.fromEntries(form);const scroll_cycle=form.getAll('scroll_cycle');await json('/api/display/apply',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({profile_id:current.profile.id,brightness:Number(v.brightness),service:v.service,destination:v.destination,route:v.route,through_route:v.through_route,service_change:v.service_change,next_stop:v.next_stop,scroll_text:v.scroll_text,scroll_speed:Number(v.scroll_speed),scroll_cycle})});message('表示内容を適用しました。')}catch(e){message(e.message)}};
$('#stop').onclick=async()=>{try{await json('/api/display/stop',{method:'POST'});message('停止しました。現在の表示を維持します。')}catch(e){message(e.message)}};
$('#blank').onclick=async()=>{try{await json('/api/display/blank',{method:'POST'});message('消灯しました。')}catch(e){message(e.message)}};
$('#test').onclick=async()=>{try{await json('/api/display/test',{method:'POST'});message('テストパターンを表示しています。')}catch(e){message(e.message)}};
setInterval(()=>{$('#preview').src=`/api/display/preview.png?t=${Date.now()}`},1000/30);
init().catch(e=>message(e.message));
